# Generated by Django 5.0.2 on 2025-06-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="github_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_github_user",
            field=models.BooleanField(default=False),
        ),
    ]
