# Generated by Django 5.0.2 on 2025-06-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="liked",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True=liked, False=disliked, None=no action",
                null=True,
            ),
        ),
    ]
