# Generated by Django 5.0.2 on 2025-06-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_message_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_feedback_message",
            field=models.TextField(
                blank=True, help_text="User feedback on AI messages", null=True
            ),
        ),
    ]
