# Generated by Django 5.0.2 on 2025-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_github_avatar_url_user_github_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="role",
        ),
        migrations.AddField(
            model_name="message",
            name="assistant_content",
            field=models.TextField(
                default="", help_text="Assistant's response content"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user_content",
            field=models.TextField(default="", help_text="User's message content"),
        ),
    ]
