# Generated by Django 5.0.2 on 2025-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_github_avatar_url_user_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_apple_user',
            field=models.BooleanField(default=False),
        ),
    ]
