# Generated by Django 5.0.2 on 2025-06-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_message_content_remove_message_role_and_more'),
        ('api', '0003_user_apple_id_user_is_apple_user'),
    ]

    operations = [
    ]
