# Generated by Django 5.0.2 on 2025-06-05 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_resource"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="resource",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="file_size",
        ),
    ]
