# Generated by Django 5.0.2 on 2025-06-05 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_resource_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
